title: "Data Mining in Python"
theme: jekyll-theme-cayman
description: "By Zhaohu(Jonathan) Fan, Harsh Singal and Yan Yu. <br /> Life is short (You need Python). ---Bruce Eckel"
github:
  is_project_page: false
