title: "Data Mining in Python"
theme: jekyll-theme-minimal

description: >
  Teaching materials for data mining and business analytics courses.

logo: /assets/img/DM.jpg   # optional if you add a logo
show_downloads: false
github:
  is_project_page: false
